// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WBSync.Data;

#nullable disable

namespace WBSync.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621014233_AddProductivityCoefficient")]
    partial class AddProductivityCoefficient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("WBSync.Models.Assignee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("DATETIME('now', 'localtime')");

                    b.Property<int?>("GlobalAssigneeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("global_assignee_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal>("ProductivityCoefficient")
                        .HasColumnType("TEXT")
                        .HasColumnName("productivity_coefficient");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("DATETIME('now', 'localtime')");

                    b.HasKey("Id");

                    b.HasIndex("GlobalAssigneeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("assignees");
                });

            modelBuilder.Entity("WBSync.Models.AssigneeHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AssigneeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("assignee_id");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT")
                        .HasColumnName("memo");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("idx_assignee_holidays_assignee_id");

                    b.HasIndex("AssigneeId", "Date")
                        .IsUnique()
                        .HasDatabaseName("idx_assignee_holidays_assignee_date");

                    b.ToTable("assignee_holidays");
                });

            modelBuilder.Entity("WBSync.Models.GlobalAssignee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal>("ProductivityCoefficient")
                        .HasColumnType("TEXT")
                        .HasColumnName("productivity_coefficient");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_global_assignees_name");

                    b.ToTable("global_assignees");
                });

            modelBuilder.Entity("WBSync.Models.GlobalHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("idx_global_holidays_date");

                    b.ToTable("global_holidays");
                });

            modelBuilder.Entity("WBSync.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("DATETIME('now', 'localtime')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("DATETIME('now', 'localtime')");

                    b.HasKey("Id");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("WBSync.Models.WbsTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("assignee_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("DATETIME('now', 'localtime')");

                    b.Property<string>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.Property<int?>("PredecessorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("predecessor_id");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("未着手")
                        .HasColumnName("status");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("DATETIME('now', 'localtime')");

                    b.Property<double?>("WorkDays")
                        .HasColumnType("REAL")
                        .HasColumnName("work_days");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("idx_tasks_parent_id");

                    b.HasIndex("PredecessorId")
                        .HasDatabaseName("idx_tasks_predecessor_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_tasks_project_id");

                    b.ToTable("tasks", t =>
                        {
                            t.HasCheckConstraint("CK_tasks_progress", "progress >= 0 AND progress <= 100");

                            t.HasCheckConstraint("CK_tasks_status", "status IN ('未着手', '進行中', '完了', '保留')");
                        });
                });

            modelBuilder.Entity("WBSync.Models.Assignee", b =>
                {
                    b.HasOne("WBSync.Models.GlobalAssignee", "GlobalAssignee")
                        .WithMany("ProjectAssignees")
                        .HasForeignKey("GlobalAssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WBSync.Models.Project", "Project")
                        .WithMany("Assignees")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalAssignee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WBSync.Models.AssigneeHoliday", b =>
                {
                    b.HasOne("WBSync.Models.Assignee", "Assignee")
                        .WithMany("Holidays")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("WBSync.Models.WbsTask", b =>
                {
                    b.HasOne("WBSync.Models.Assignee", "Assignee")
                        .WithMany("Tasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WBSync.Models.WbsTask", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WBSync.Models.WbsTask", "Predecessor")
                        .WithMany()
                        .HasForeignKey("PredecessorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WBSync.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Parent");

                    b.Navigation("Predecessor");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WBSync.Models.Assignee", b =>
                {
                    b.Navigation("Holidays");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("WBSync.Models.GlobalAssignee", b =>
                {
                    b.Navigation("ProjectAssignees");
                });

            modelBuilder.Entity("WBSync.Models.Project", b =>
                {
                    b.Navigation("Assignees");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("WBSync.Models.WbsTask", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
